import { Medicine, HealthArticle, Order } from '@/types'

export const MEDICINES: Medicine[] = [
  {
    id: 'm1',
    name: 'Imatinib 400mg',
    genericName: 'Imatinib Mesylate',
    manufacturer: 'Natco Pharma',
    category: 'cancer',
    mrp: 18000,
    drmedPrice: 2700,
    discountPercent: 85,
    inStock: true,
    stockLevel: 'high',
    requiresPrescription: true,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80',
    description: 'Imatinib is used to treat certain types of leukemia (blood cancer) and other cancers of the blood cells. It belongs to a class of drugs called kinase inhibitors.',
    uses: ['Chronic Myeloid Leukemia (CML)', 'Acute Lymphoblastic Leukemia (ALL)', 'Gastrointestinal Stromal Tumors (GIST)'],
    sideEffects: {
      common: ['Nausea', 'Muscle cramps', 'Fatigue', 'Diarrhea', 'Skin rash'],
      serious: ['Fluid retention (swelling)', 'Liver problems', 'Heart failure', 'Severe skin reactions'],
      emergency: ['Difficulty breathing', 'Sudden chest pain', 'Severe swelling of face/throat'],
    },
    dosage: '400mg once daily with a meal and a large glass of water. Do not crush or break the tablet.',
    storage: 'Store below 30°C. Keep away from moisture and direct sunlight.',
    coldChain: false,
    saltComposition: 'Imatinib Mesylate 400mg',
    rating: 4.8,
    reviewCount: 342,
    tags: ['leukemia', 'CML', 'kinase inhibitor', 'cancer'],
  },
  {
    id: 'm2',
    name: 'Trastuzumab 440mg',
    genericName: 'Trastuzumab',
    manufacturer: 'Roche / Emcure',
    category: 'cancer',
    mrp: 75000,
    drmedPrice: 22500,
    discountPercent: 70,
    inStock: true,
    stockLevel: 'low',
    requiresPrescription: true,
    imageUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&q=80',
    description: 'Trastuzumab (Herceptin) is a targeted therapy for HER2-positive breast cancer and stomach cancer. It works by blocking the HER2 protein that causes cancer cells to grow.',
    uses: ['HER2-positive Breast Cancer', 'HER2-positive Gastric Cancer'],
    sideEffects: {
      common: ['Fever', 'Chills', 'Headache', 'Diarrhea', 'Fatigue'],
      serious: ['Heart problems', 'Lung problems', 'Severe allergic reactions'],
      emergency: ['Severe shortness of breath', 'Irregular heartbeat', 'Severe chest pain'],
    },
    dosage: 'Administered via IV infusion. Dosage determined by your oncologist based on body weight.',
    storage: 'Refrigerate at 2–8°C. Do not freeze. Cold chain required.',
    coldChain: true,
    saltComposition: 'Trastuzumab 440mg',
    rating: 4.9,
    reviewCount: 178,
    tags: ['HER2', 'breast cancer', 'targeted therapy', 'biologics'],
  },
  {
    id: 'm3',
    name: 'Tenofovir 300mg',
    genericName: 'Tenofovir Disoproxil Fumarate',
    manufacturer: 'Cipla',
    category: 'hiv',
    mrp: 2800,
    drmedPrice: 420,
    discountPercent: 85,
    inStock: true,
    stockLevel: 'high',
    requiresPrescription: true,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&q=80',
    description: 'Tenofovir is an antiretroviral medicine used in combination with other HIV medicines to treat HIV infection and reduce the viral load in the blood.',
    uses: ['HIV-1 infection (in combination therapy)', 'Chronic Hepatitis B'],
    sideEffects: {
      common: ['Nausea', 'Diarrhea', 'Headache', 'Fatigue', 'Dizziness'],
      serious: ['Kidney problems', 'Decreased bone density', 'Lactic acidosis'],
      emergency: ['Severe weakness', 'Unusual muscle pain', 'Trouble breathing'],
    },
    dosage: '300mg once daily, with or without food. Take at the same time every day.',
    storage: 'Store below 25°C in a dry place.',
    coldChain: false,
    saltComposition: 'Tenofovir Disoproxil Fumarate 300mg',
    rating: 4.7,
    reviewCount: 521,
    tags: ['HIV', 'antiretroviral', 'ART', 'hepatitis B'],
  },
  {
    id: 'm4',
    name: 'Tacrolimus 1mg',
    genericName: 'Tacrolimus',
    manufacturer: 'Astellas / Panacea',
    category: 'transplant',
    mrp: 9500,
    drmedPrice: 3800,
    discountPercent: 60,
    inStock: true,
    stockLevel: 'high',
    requiresPrescription: true,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80',
    description: 'Tacrolimus is an immunosuppressant medicine used to prevent organ rejection after kidney, liver, or heart transplant.',
    uses: ['Kidney transplant rejection prevention', 'Liver transplant rejection prevention', 'Heart transplant rejection prevention'],
    sideEffects: {
      common: ['Tremor', 'Headache', 'Diarrhea', 'Nausea', 'High blood pressure'],
      serious: ['Kidney toxicity', 'Increased infection risk', 'High blood sugar', 'Neurotoxicity'],
      emergency: ['Signs of infection (fever, chills)', 'Severe kidney problems', 'Seizures'],
    },
    dosage: 'Dose varies by organ type and blood levels. Take exactly as prescribed — never skip a dose.',
    storage: 'Store below 25°C. Keep in original blister pack.',
    coldChain: false,
    saltComposition: 'Tacrolimus 1mg',
    rating: 4.6,
    reviewCount: 234,
    tags: ['transplant', 'immunosuppressant', 'kidney', 'liver'],
  },
  {
    id: 'm5',
    name: 'Sofosbuvir 400mg',
    genericName: 'Sofosbuvir',
    manufacturer: 'Gilead / Hetero',
    category: 'hepatitis',
    mrp: 28000,
    drmedPrice: 5600,
    discountPercent: 80,
    inStock: true,
    stockLevel: 'high',
    requiresPrescription: true,
    imageUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&q=80',
    description: 'Sofosbuvir is a direct-acting antiviral used to treat Hepatitis C infection. It is a core component of highly effective, short-duration Hepatitis C treatment regimens.',
    uses: ['Chronic Hepatitis C (all genotypes)'],
    sideEffects: {
      common: ['Fatigue', 'Headache', 'Nausea', 'Insomnia'],
      serious: ['Serious heart rhythm problems (when used with amiodarone)', 'Hepatitis B reactivation'],
      emergency: ['Slow or irregular heartbeat', 'Dizziness or fainting', 'Shortness of breath'],
    },
    dosage: '400mg once daily with or without food for 12 weeks (duration depends on genotype).',
    storage: 'Store below 30°C. Keep in original container.',
    coldChain: false,
    saltComposition: 'Sofosbuvir 400mg',
    rating: 4.9,
    reviewCount: 389,
    tags: ['hepatitis C', 'antiviral', 'HCV', 'direct-acting antiviral'],
  },
  {
    id: 'm6',
    name: 'Amlodipine 5mg',
    genericName: 'Amlodipine Besylate',
    manufacturer: 'Sun Pharma',
    category: 'heart',
    mrp: 180,
    drmedPrice: 54,
    discountPercent: 70,
    inStock: true,
    stockLevel: 'high',
    requiresPrescription: true,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&q=80',
    description: 'Amlodipine is a calcium channel blocker used to treat high blood pressure (hypertension) and chest pain (angina).',
    uses: ['High Blood Pressure (Hypertension)', 'Stable Angina', 'Vasospastic Angina'],
    sideEffects: {
      common: ['Ankle swelling', 'Flushing', 'Headache', 'Dizziness', 'Fatigue'],
      serious: ['Very low blood pressure', 'Worsening angina', 'Liver problems'],
      emergency: ['Severe dizziness or fainting', 'Irregular heartbeat', 'Chest pain that worsens'],
    },
    dosage: '5mg once daily. May be increased to 10mg based on response.',
    storage: 'Store at room temperature (15–30°C). Protect from light.',
    coldChain: false,
    saltComposition: 'Amlodipine Besylate 5mg',
    rating: 4.5,
    reviewCount: 892,
    tags: ['blood pressure', 'hypertension', 'calcium channel blocker', 'heart'],
  },
  {
    id: 'm7',
    name: 'Methotrexate 2.5mg',
    genericName: 'Methotrexate',
    manufacturer: 'Ipca Laboratories',
    category: 'arthritis',
    mrp: 420,
    drmedPrice: 105,
    discountPercent: 75,
    inStock: true,
    stockLevel: 'high',
    requiresPrescription: true,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80',
    description: 'Methotrexate is a disease-modifying antirheumatic drug (DMARD) used to treat rheumatoid arthritis, psoriatic arthritis, and certain cancers.',
    uses: ['Rheumatoid Arthritis', 'Psoriatic Arthritis', 'Juvenile Idiopathic Arthritis'],
    sideEffects: {
      common: ['Nausea', 'Mouth sores', 'Fatigue', 'Hair thinning'],
      serious: ['Liver toxicity', 'Lung problems', 'Bone marrow suppression'],
      emergency: ['Severe nausea/vomiting', 'Mouth sores that prevent eating', 'Signs of infection'],
    },
    dosage: 'Usually taken once a week (not daily). Always take folic acid as prescribed alongside.',
    storage: 'Store at room temperature. Keep out of reach of children.',
    coldChain: false,
    saltComposition: 'Methotrexate 2.5mg',
    rating: 4.4,
    reviewCount: 456,
    tags: ['rheumatoid arthritis', 'DMARD', 'psoriasis', 'immunosuppressant'],
  },
  {
    id: 'm8',
    name: 'Erythropoietin 4000 IU',
    genericName: 'Epoetin Alfa',
    manufacturer: 'Wockhardt',
    category: 'kidney',
    mrp: 3200,
    drmedPrice: 1280,
    discountPercent: 60,
    inStock: true,
    stockLevel: 'high',
    requiresPrescription: true,
    imageUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&q=80',
    description: 'Erythropoietin (EPO) stimulates the production of red blood cells and is used to treat anaemia in patients with chronic kidney disease.',
    uses: ['Anaemia in Chronic Kidney Disease', 'Anaemia in Dialysis Patients', 'Chemotherapy-related Anaemia'],
    sideEffects: {
      common: ['Headache', 'Joint pain', 'Nausea', 'Injection site reaction'],
      serious: ['High blood pressure', 'Blood clots', 'Pure red cell aplasia'],
      emergency: ['Stroke symptoms', 'Heart attack symptoms', 'Severe allergic reaction'],
    },
    dosage: 'Administered by injection (subcutaneous or intravenous). Dose determined by kidney specialist.',
    storage: 'Refrigerate at 2–8°C. Do not freeze or shake. Cold chain required.',
    coldChain: true,
    saltComposition: 'Epoetin Alfa 4000 IU/mL',
    rating: 4.7,
    reviewCount: 198,
    tags: ['kidney', 'anaemia', 'dialysis', 'erythropoietin'],
  },
]

export const HEALTH_ARTICLES: HealthArticle[] = [
  {
    id: 'a1',
    title: 'Understanding CML: What Is Chronic Myeloid Leukemia?',
    slug: 'understanding-cml-chronic-myeloid-leukemia',
    category: 'Cancer Care',
    excerpt: 'A complete guide to CML — symptoms, diagnosis, and how targeted therapy like Imatinib has transformed treatment outcomes.',
    readTime: 7,
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
    publishedAt: '2026-05-12',
    author: 'Dr. Priya Nair, Oncologist',
  },
  {
    id: 'a2',
    title: 'Living with Kidney Disease: A Patient\'s Guide to Daily Management',
    slug: 'living-with-kidney-disease-daily-management',
    category: 'Kidney Care',
    excerpt: 'From diet changes to medication schedules, here\'s everything you need to know about managing chronic kidney disease at home.',
    readTime: 9,
    imageUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=600&q=80',
    publishedAt: '2026-04-28',
    author: 'Dr. Rajan Menon, Nephrologist',
  },
  {
    id: 'a3',
    title: 'Hepatitis C Treatment in 2026: A Cure Within 12 Weeks',
    slug: 'hepatitis-c-treatment-2026-cure',
    category: 'Hepatitis',
    excerpt: 'Modern direct-acting antivirals like Sofosbuvir have made Hepatitis C one of the most curable chronic viral infections.',
    readTime: 6,
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80',
    publishedAt: '2026-05-30',
    author: 'Dr. Sunita Rao, Hepatologist',
  },
  {
    id: 'a4',
    title: 'What Are Patient Assistance Programs? Your Guide to Free Medicines',
    slug: 'patient-assistance-programs-free-medicines',
    category: 'Financial Aid',
    excerpt: 'Many pharmaceutical companies offer free or subsidised specialty medicines. Here\'s how to apply and what to expect.',
    readTime: 5,
    imageUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=600&q=80',
    publishedAt: '2026-05-05',
    author: 'DrMed Pharmacy Team',
  },
]

export const MOCK_ORDER: Order = {
  id: 'ORD-2026-001234',
  createdAt: '2026-06-12T10:30:00Z',
  status: 'dispatched',
  items: [
    { medicine: MEDICINES[0], quantity: 1, prescriptionUploaded: true },
    { medicine: MEDICINES[2], quantity: 2, prescriptionUploaded: true },
  ],
  totalAmount: 3540,
  deliveryAddress: {
    name: 'Thirumurugan',
    line1: '45, Anna Nagar East',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600102',
    phone: '98765 43210',
  },
  estimatedDelivery: '2026-06-15',
  trackingEvents: [
    { status: 'Order Placed', timestamp: '2026-06-12T10:30:00Z', location: 'Online' },
    { status: 'Prescription Verified', timestamp: '2026-06-12T14:00:00Z', location: 'DrMed Pharmacy, Chennai' },
    { status: 'Order Confirmed', timestamp: '2026-06-12T14:15:00Z', location: 'DrMed Warehouse, Chennai' },
    { status: 'Dispatched', timestamp: '2026-06-13T09:00:00Z', location: 'DrMed Hub, Chennai' },
  ],
}

export const CONDITIONS = [
  { id: 'cancer',    label: 'Cancer',     icon: '🎗️', color: 'from-rose-500 to-red-600',      count: 1240 },
  { id: 'kidney',    label: 'Kidney Care',icon: '🫘', color: 'from-blue-500 to-blue-700',      count: 380 },
  { id: 'hiv',       label: 'HIV/AIDS',   icon: '🔴', color: 'from-red-500 to-orange-500',     count: 290 },
  { id: 'hepatitis', label: 'Hepatitis',  icon: '🫀', color: 'from-amber-500 to-yellow-500',   count: 210 },
  { id: 'heart',     label: 'Heart Care', icon: '❤️', color: 'from-pink-500 to-rose-500',      count: 680 },
  { id: 'arthritis', label: 'Arthritis',  icon: '🦴', color: 'from-indigo-500 to-purple-600',  count: 450 },
  { id: 'diabetes',  label: 'Diabetes',   icon: '💉', color: 'from-teal-500 to-green-600',     count: 920 },
  { id: 'transplant',label: 'Transplant', icon: '🫁', color: 'from-violet-500 to-purple-700',  count: 175 },
]
